from fpdf import FPDF
import re

# --- WEB UI RENDERER: SOUTH INDIAN CHART (HTML/CSS) ---
def get_south_indian_chart_html(p_pos, lagna_rasi, title="Rasi Chart", lang="English"):
    """Generates a responsive CSS-grid South Indian style chart for the Web UI."""
    grid = {i: [] for i in range(1, 13)}
    
    # Map planets to houses
    for p, rasi in p_pos.items():
        if rasi in grid:
            label = p[:2].upper() if p not in ["Lagna", "Rahu", "Ketu"] else p[:2]
            if p == "Lagna": label = "Asc"
            grid[rasi].append(label)
            
    # Tamil translation mapping for standard labels
    def t(eng_txt):
        if lang == "English": return eng_txt
        mapping = {"Asc": "லக்", "SU": "சூ", "MO": "சந்", "MA": "செ", "ME": "பு", "JU": "கு", "VE": "சுக்", "SA": "சனி", "Ra": "ரா", "Ke": "கே"}
        return mapping.get(eng_txt, eng_txt)

    def get_box(rasi_num):
        planets = " ".join([f"<span style='display:inline-block; margin:2px; padding:2px 4px; background:#e8f6f3; color:#16a085; border-radius:3px; font-size:11px; font-weight:bold;'>{t(p)}</span>" for p in grid[rasi_num]])
        return f"<div style='border: 1px solid #ccc; height: 90px; padding: 5px; background: #fff;'>{planets}</div>"

    html = f"""
    <div style="max-width: 400px; margin: 0 auto; font-family: sans-serif;">
        <div style="text-align: center; margin-bottom: 10px; font-weight: bold; color: #2c3e50;">{title}</div>
        <div style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 0; background: #ecf0f1; padding: 2px;">
            {get_box(12)} {get_box(1)} {get_box(2)} {get_box(3)}
            {get_box(11)} <div style="grid-column: span 2; grid-row: span 2; display: flex; align-items: center; justify-content: center; background: #fdfdfd; font-size: 14px; color: #bdc3c7; border: 1px solid #ccc;">{title}</div> {get_box(4)}
            {get_box(10)} {get_box(5)}
            {get_box(9)} {get_box(8)} {get_box(7)} {get_box(6)}
        </div>
    </div>
    """
    return html


# --- PDF GENERATOR ENGINE (FPDF2) ---
class ExecutivePDF(FPDF):
    def header(self):
        self.set_font('helvetica', 'B', 16)
        self.set_text_color(44, 62, 80)
        self.cell(0, 10, 'Strategic Astrological Blueprint', border=False, align='C')
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Vedic Astro AI', 0, 0, 'C')

    def chapter_title(self, title):
        self.set_font('helvetica', 'B', 14)
        self.set_text_color(22, 160, 133) # Teal
        self.cell(0, 10, title, 0, 1, 'L')
        self.set_draw_color(22, 160, 133)
        self.line(self.get_x(), self.get_y(), self.get_x() + 190, self.get_y())
        self.ln(5)

    def chapter_body(self, body):
        self.set_font('helvetica', '', 11)
        self.set_text_color(50, 50, 50)
        self.multi_cell(0, 6, body)
        self.ln(5)

def clean_text(text):
    """Strips HTML tags and Markdown formatting so FPDF doesn't crash."""
    if not isinstance(text, str):
        return ""
    text = re.sub(r'<[^>]+>', '', text) # Remove HTML
    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text) # Remove bold markdown
    text = re.sub(r'_(.*?)_', r'\1', text) # Remove italic markdown
    text = re.sub(r'#(.*)', '', text) # Remove Headers
    return text.strip()

def generate_pdf_report(**kwargs):
    """
    Compiles all AI and mathematical data into a multi-page PDF.
    Expects kwargs matching the ones passed from 2_deep_horoscope.py
    """
    try:
        pdf = ExecutivePDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)

        # 1. PROFILE HEADER
        pdf.set_font('helvetica', 'B', 20)
        pdf.set_text_color(44, 62, 80)
        pdf.cell(0, 10, f"Executive Profile: {kwargs.get('name_in', 'Client')}", 0, 1, 'C')
        pdf.ln(5)
        
        pdf.set_font('helvetica', '', 12)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 6, f"Lagna (Ascendant): {kwargs.get('lagna_str', '')}", 0, 1, 'C')
        pdf.cell(0, 6, f"Moon Sign (Rasi): {kwargs.get('moon_str', '')}", 0, 1, 'C')
        pdf.cell(0, 6, f"Birth Star (Nakshatra): {kwargs.get('star_str', '')}", 0, 1, 'C')
        pdf.ln(10)

        # 2. PLANETARY MATRIX (Table)
        pdf.chapter_title("Planetary Core Matrix")
        master_table = kwargs.get('master_table', [])
        
        # Table Header
        pdf.set_font('helvetica', 'B', 10)
        pdf.set_fill_color(240, 240, 240)
        col_widths = [35, 35, 25, 45, 45]
        headers = ["Planet", "Sign (Rasi)", "House", "Dignity", "Status"]
        
        for i, header in enumerate(headers):
            pdf.cell(col_widths[i], 8, header, 1, 0, 'C', 1)
        pdf.ln()

        # Table Rows
        pdf.set_font('helvetica', '', 10)
        for row in master_table:
            pdf.cell(col_widths[0], 8, str(row.get('Planet', '')), 1, 0, 'C')
            pdf.cell(col_widths[1], 8, str(row.get('Rasi', '')), 1, 0, 'C')
            pdf.cell(col_widths[2], 8, str(row.get('House', '')), 1, 0, 'C')
            pdf.cell(col_widths[3], 8, str(row.get('Dignity', '')), 1, 0, 'C')
            pdf.cell(col_widths[4], 8, str(row.get('Status', '')), 1, 0, 'C')
            pdf.ln()
        pdf.ln(10)

        # 3. EXECUTIVE PLAYBOOK (MBTI & Enneagram)
        pdf.chapter_title("Psychological & Strategic Execution")
        mbti = kwargs.get('mbti_data', {})
        ennea = kwargs.get('ennea_data', {})
        
        playbook_text = f"Cognitive Framework (MBTI): {mbti.get('code', 'Unknown')}\n\n"
        playbook_text += f"Core Driver (Atmakaraka): {ennea.get('ak_planet', '')} - {ennea.get('ak_type', '')}\n"
        playbook_text += f"{clean_text(ennea.get('ak_coaching', ''))}\n\n"
        playbook_text += f"Execution Wing (Amatyakaraka): {ennea.get('amk_planet', '')}\n"
        playbook_text += f"{clean_text(ennea.get('amk_coaching', ''))}\n\n"
        
        coaching = kwargs.get('coaching_rules', [])
        if coaching:
            playbook_text += "Executive Rules for Success:\n"
            for i, rule in enumerate(coaching):
                playbook_text += f"{i+1}. {clean_text(rule)}\n"
        
        pdf.chapter_body(playbook_text)

        # 4. CAREER & KARMIC PATH
        pdf.add_page()
        pdf.chapter_title("Career & Zone of Genius")
        career_list = kwargs.get('career_txt', [])
        career_body = "\n\n".join([clean_text(item) for item in career_list])
        pdf.chapter_body(career_body)
        
        pdf.chapter_title("Karmic Directives (Rahu/Ketu)")
        karmic_list = kwargs.get('karmic_txt', [])
        karmic_body = "\n\n".join([clean_text(item) for item in karmic_list])
        pdf.chapter_body(karmic_body)

        # 5. TIMELINE FORECAST
        pdf.chapter_title("Vimshottari Dasha (Timeline)")
        dasha_data = kwargs.get('mahadasha_data', [])
        
        # Dasha Table Header
        pdf.set_font('helvetica', 'B', 10)
        pdf.cell(30, 8, "Age", 1, 0, 'C', 1)
        pdf.cell(40, 8, "Years", 1, 0, 'C', 1)
        pdf.cell(30, 8, "Phase", 1, 0, 'C', 1)
        pdf.ln()
        
        pdf.set_font('helvetica', '', 10)
        for row in dasha_data:
            pdf.cell(30, 8, str(row.get('Age (From-To)', '')), 1, 0, 'C')
            pdf.cell(40, 8, str(row.get('Years', '')), 1, 0, 'C')
            pdf.cell(30, 8, str(row.get('Mahadasha', '')), 1, 0, 'C')
            pdf.ln()

        # Ensure output works smoothly with Streamlit's download button
        pdf_output = pdf.output(dest='S')
        # FPDF output('S') returns a string in older versions, bytes in newer. 
        # We ensure it is encoded properly to bytes.
        if isinstance(pdf_output, str):
            pdf_output = pdf_output.encode('latin-1')

        return pdf_output, None

    except Exception as e:
        return None, str(e)
