from fpdf import FPDF
import re

# --- WEB UI RENDERER: SOUTH INDIAN CHART (HTML/CSS) ---
def get_south_indian_chart_html(p_pos, lagna_rasi, title="Rasi Chart", lang="English", user_name=""):
    """
    Generates a traditional South Indian style chart for the Web UI.
    Features 1px grey borders, corner zodiac names, dynamic House (H1, H2) numbers,
    stacked bold planets, and a very subtle red diagonal strike-through for the Lagna.
    """
    grid = {i: [] for i in range(1, 13)}
    
    # Map planets to houses
    for p, rasi in p_pos.items():
        if rasi in grid:
            if p == "Lagna": 
                label = "Asc"
            elif p in ["Rahu", "Ketu"]:
                label = p[:2].capitalize()
            else:
                label = p[:2].capitalize()
            grid[rasi].append(label)
            
    # Tamil translation mapping for standard labels
    def t(eng_txt):
        if lang == "English": return eng_txt
        mapping = {"Asc": "லக்", "Su": "சூ", "Mo": "சந்", "Ma": "செ", "Me": "பு", "Ju": "கு", "Ve": "சுக்", "Sa": "சனி", "Ra": "ரா", "Ke": "கே"}
        return mapping.get(eng_txt, eng_txt)

    zodiac_names_en = {1: "Mesha", 2: "Rishabha", 3: "Mithuna", 4: "Kataka", 5: "Simha", 6: "Kanya", 7: "Thula", 8: "Vrischika", 9: "Dhanu", 10: "Makara", 11: "Kumbha", 12: "Meena"}
    zodiac_names_ta = {1: "மேஷம்", 2: "ரிஷபம்", 3: "மிதுனம்", 4: "கடகம்", 5: "சிம்மம்", 6: "கன்னி", 7: "துலாம்", 8: "விருச்சிகம்", 9: "தனுசு", 10: "மகரம்", 11: "கும்பம்", 12: "மீனம்"}
    z_names = zodiac_names_ta if lang == "Tamil" else zodiac_names_en

    def get_box(rasi_num):
        is_lagna = (rasi_num == lagna_rasi)
        
        house_num = (rasi_num - lagna_rasi + 1) if (rasi_num - lagna_rasi + 1) > 0 else (rasi_num - lagna_rasi + 1) + 12
        house_label = f"H{house_num}"
        
        # Traditional, very subtle red slanting line for Ascendant (Lagna)
        if is_lagna:
            bg_style = "background: linear-gradient(to bottom right, transparent calc(50% - 0.5px), rgba(220, 53, 69, 0.3) calc(50% - 0.5px), rgba(220, 53, 69, 0.3) calc(50% + 0.5px), transparent calc(50% + 0.5px)) #ffffff;"
        else:
            bg_style = "background: #ffffff;"
            
        rasi_name = z_names.get(rasi_num, "")
        
        # Bold, black, center-stacked planets
        planets_formatted = "".join([f"<div style='margin-bottom:2px;'>{t(p)}</div>" for p in grid[rasi_num]])
        
        return f"<div style='position: relative; {bg_style} aspect-ratio: 1/1; min-height: 110px; display: flex; flex-direction: column; justify-content: center; align-items: center;'><div style='font-size: 11.5px; color: #95a5a6; position: absolute; top: 6px; left: 8px;'>{rasi_name}</div><div style='font-size: 11px; color: #bdc3c7; font-weight: 600; position: absolute; top: 6px; right: 8px;'>{house_label}</div><div style='font-size: 16px; font-weight: 800; color: #111; line-height: 1.2;'>{planets_formatted}</div></div>"

    b12, b1, b2, b3 = get_box(12), get_box(1), get_box(2), get_box(3)
    b11, b4 = get_box(11), get_box(4)
    b10, b5 = get_box(10), get_box(5)
    b9, b8, b7, b6 = get_box(9), get_box(8), get_box(7), get_box(6)
    
    name_html = f"<div style='font-size: 15px; color: #7f8c8d; font-weight: normal; margin-top: 6px;'>{user_name}</div>" if user_name else ""
    center_div = f"<div style='grid-column: span 2; grid-row: span 2; display: flex; flex-direction: column; align-items: center; justify-content: center; background: #ffffff;'><div style='font-size: 20px; font-weight: 800; color: #2c3e50;'>{title}</div>{name_html}</div>"
    
    html = f"<div style='max-width: 520px; margin: 0 auto; font-family: \"Helvetica Neue\", Helvetica, Arial, sans-serif;'><div style='display: grid; grid-template-columns: repeat(4, 1fr); gap: 1px; background-color: #cccccc; border: 1px solid #cccccc;'>{b12}{b1}{b2}{b3}{b11}{center_div}{b4}{b10}{b5}{b9}{b8}{b7}{b6}</div></div>"
    return html


# --- PDF GENERATOR ENGINE (FPDF2) ---
class ExecutivePDF(FPDF):
    def header(self):
        self.set_font('helvetica', 'B', 16)
        self.set_text_color(44, 62, 80)
        self.cell(0, 10, 'Strategic Astrological Blueprint', border=False, align='C')
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Vedic Astro AI', 0, 0, 'C')

    def chapter_title(self, title):
        self.set_font('helvetica', 'B', 14)
        self.set_text_color(22, 160, 133)
        self.cell(0, 10, title, 0, 1, 'L')
        self.set_draw_color(22, 160, 133)
        self.line(self.get_x(), self.get_y(), self.get_x() + 190, self.get_y())
        self.ln(5)

    def chapter_body(self, body):
        if not body: return
        self.set_font('helvetica', '', 11)
        self.set_text_color(50, 50, 50)
        self.multi_cell(0, 6, body)
        self.ln(5)

    def draw_pdf_chart(self, p_pos, lagna_rasi, title="Birth Chart (Rasi)"):
        """Draws the physical 4x4 grid chart directly onto the PDF."""
        # Ensure we have enough space, else add a page
        if self.get_y() > 150:
            self.add_page()
            
        self.ln(5)
        start_y = self.get_y()
        box_w, box_h = 32, 32
        start_x = (210 - (box_w * 4)) / 2  # Center horizontally on A4
        
        grid = {i: [] for i in range(1, 13)}
        for p, rasi in p_pos.items():
            if rasi in grid:
                label = "Asc" if p == "Lagna" else p[:2].capitalize()
                grid[rasi].append(label)
                
        positions = {
            12: (0, 0), 1: (1, 0), 2: (2, 0), 3: (3, 0),
            11: (0, 1),                        4: (3, 1),
            10: (0, 2),                        5: (3, 2),
            9:  (0, 3), 8: (1, 3), 7: (2, 3), 6: (3, 3)
        }
        
        self.set_draw_color(180, 180, 180)
        self.set_line_width(0.3)
        
        for rasi, (col, row) in positions.items():
            x = start_x + (col * box_w)
            y = start_y + (row * box_h)
            self.rect(x, y, box_w, box_h)
            
            # House Number
            house_num = (rasi - lagna_rasi + 1) if (rasi - lagna_rasi + 1) > 0 else (rasi - lagna_rasi + 1) + 12
            self.set_xy(x, y + 2)
            self.set_font('helvetica', '', 7)
            self.set_text_color(160, 160, 160)
            self.cell(box_w - 2, 4, f"H{house_num}", 0, 0, 'R')
            
            # Planets
            if grid[rasi]:
                planets_str = "\n".join(grid[rasi])
                self.set_xy(x, y + 8)
                self.set_font('helvetica', 'B', 10)
                self.set_text_color(20, 20, 20)
                self.multi_cell(box_w, 5, planets_str, 0, 'C')
            
            # Ascendant Red Line
            if rasi == lagna_rasi:
                self.set_draw_color(220, 53, 69)
                self.set_line_width(0.4)
                self.line(x, y, x + box_w, y + box_h)
                self.set_draw_color(180, 180, 180) # Reset

        # Center Title
        self.set_xy(start_x + box_w, start_y + box_h)
        self.set_font('helvetica', 'B', 14)
        self.set_text_color(44, 62, 80)
        self.cell(box_w * 2, box_h * 2, clean_text(title), 0, 0, 'C')
        
        self.set_y(start_y + box_h * 4 + 15)


def clean_text(text):
    """Aggressively strips HTML, Markdown, and unsafe Unicode to guarantee PDF stability."""
    if not isinstance(text, str):
        return ""
    
    text = re.sub(r'<[^>]+>', '', text)
    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)
    text = re.sub(r'_(.*?)_', r'\1', text)
    text = re.sub(r'#(.*)', '', text)
    
    replacements = {
        '—': '-', '–': '-', '“': '"', '”': '"', '‘': "'", '’': "'", 
        '…': '...', '•': '-', '\u200b': '', '\u200e': '', '✨': '', '✦': ''
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
        
    text = text.encode('latin-1', 'ignore').decode('latin-1')
    return text.strip()

def generate_pdf_report(**kwargs):
    """
    Compiles all AI and mathematical data into a cohesive, multi-page PDF.
    Now includes ALL data from the Deep Horoscope tabs and renders visual grids.
    """
    try:
        pdf = ExecutivePDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)

        client_name = kwargs.get('name_in', 'Client')
        lagna_rasi = kwargs.get('lagna_rasi', 1)
        p_pos = kwargs.get('p_pos', {})
        p_d9 = kwargs.get('p_d9', {})
        navamsa_lagna = p_d9.get("Lagna", 1)

        # --- 1. PROFILE HEADER ---
        pdf.set_font('helvetica', 'B', 20)
        pdf.set_text_color(44, 62, 80)
        pdf.cell(0, 10, f"Executive Profile: {client_name}", 0, 1, 'C')
        pdf.ln(5)
        
        pdf.set_font('helvetica', '', 12)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 6, f"Lagna (Ascendant): {clean_text(kwargs.get('lagna_str', ''))}", 0, 1, 'C')
        pdf.cell(0, 6, f"Moon Sign (Rasi): {clean_text(kwargs.get('moon_str', ''))}", 0, 1, 'C')
        pdf.cell(0, 6, f"Birth Star (Nakshatra): {clean_text(kwargs.get('star_str', ''))}", 0, 1, 'C')
        pdf.ln(5)

        # --- 2. VISUAL RASI CHART ---
        pdf.draw_pdf_chart(p_pos, lagna_rasi, title="Birth Chart (Rasi)")

        # --- 3. PLANETARY MATRIX TABLE ---
        pdf.chapter_title("Planetary Core Matrix")
        master_table = kwargs.get('master_table', [])
        
        pdf.set_font('helvetica', 'B', 10)
        pdf.set_fill_color(240, 240, 240)
        pdf.set_text_color(44, 62, 80)
        col_widths = [35, 35, 25, 45, 45]
        headers = ["Planet", "Sign (Rasi)", "House", "Dignity", "Status"]
        
        for i, header in enumerate(headers):
            pdf.cell(col_widths[i], 8, header, 1, 0, 'C', 1)
        pdf.ln()

        pdf.set_font('helvetica', '', 10)
        pdf.set_text_color(50, 50, 50)
        for row in master_table:
            pdf.cell(col_widths[0], 8, clean_text(str(row.get('Planet', ''))), 1, 0, 'C')
            pdf.cell(col_widths[1], 8, clean_text(str(row.get('Rasi', ''))), 1, 0, 'C')
            pdf.cell(col_widths[2], 8, clean_text(str(row.get('House', ''))), 1, 0, 'C')
            pdf.cell(col_widths[3], 8, clean_text(str(row.get('Dignity', ''))), 1, 0, 'C')
            pdf.cell(col_widths[4], 8, clean_text(str(row.get('Status', ''))), 1, 0, 'C')
            pdf.ln()
        pdf.ln(10)

        # --- 4. EXECUTIVE PLAYBOOK ---
        pdf.add_page()
        pdf.chapter_title("Psychological & Strategic Execution")
        mbti = kwargs.get('mbti_data', {})
        ennea = kwargs.get('ennea_data', {})
        
        playbook_text = f"Cognitive Framework (MBTI): {clean_text(str(mbti.get('code', 'Unknown')))}\n\n"
        playbook_text += f"Core Driver (Atmakaraka): {clean_text(str(ennea.get('ak_planet', '')))} - {clean_text(str(ennea.get('ak_type', '')))}\n"
        playbook_text += f"{clean_text(str(ennea.get('ak_coaching', '')))}\n\n"
        playbook_text += f"Execution Wing (Amatyakaraka): {clean_text(str(ennea.get('amk_planet', '')))}\n"
        playbook_text += f"{clean_text(str(ennea.get('amk_coaching', '')))}\n\n"
        
        coaching = kwargs.get('coaching_rules', [])
        if coaching:
            playbook_text += "Executive Rules for Success:\n"
            for i, rule in enumerate(coaching):
                playbook_text += f"{i+1}. {clean_text(str(rule))}\n"
        
        pdf.chapter_body(playbook_text)

        # --- 5. CAREER & KARMIC PATH ---
        pdf.chapter_title("Career & Zone of Genius")
        career_list = kwargs.get('career_txt', [])
        pdf.chapter_body("\n\n".join([clean_text(str(item)) for item in career_list]))
        
        pdf.chapter_title("Karmic Directives (Rahu/Ketu)")
        karmic_list = kwargs.get('karmic_txt', [])
        pdf.chapter_body("\n\n".join([clean_text(str(item)) for item in karmic_list]))

        # --- 6. EDUCATION & INTELLECT ---
        edu_list = kwargs.get('edu_txt', [])
        if edu_list:
            pdf.chapter_title("Intellect & Education")
            pdf.chapter_body("\n\n".join([clean_text(str(item)) for item in edu_list]))

        # --- 7. LOVE & HEALTH (Includes Navamsa Chart) ---
        pdf.add_page()
        pdf.chapter_title("Destiny Chart (Navamsa / D9)")
        pdf.draw_pdf_chart(p_d9, navamsa_lagna, title="Navamsa Chart")

        love_list = kwargs.get('love_txt', [])
        if love_list:
            pdf.chapter_title("Partnerships & Marriage")
            pdf.chapter_body("\n\n".join([clean_text(str(item)) for item in love_list]))

        health_list = kwargs.get('health_txt', [])
        if health_list:
            pdf.chapter_title("Vitality & Health")
            pdf.chapter_body("\n\n".join([clean_text(str(item)) for item in health_list]))

        # --- 8. YOGAS ---
        yogas = kwargs.get('yogas', [])
        if yogas:
            pdf.add_page()
            pdf.chapter_title("Key Astrological Yogas")
            for y in yogas:
                y_text = f"{clean_text(y.get('Name', ''))} ({clean_text(y.get('Type', ''))})\n"
                y_text += f"{clean_text(y.get('Description', ''))}\n"
                pdf.chapter_body(y_text)

        # --- 9. ANNUAL FORECAST ---
        fc = kwargs.get('fc', {})
        if fc:
            pdf.chapter_title("Annual Forecast & Remedy")
            for cat, data in fc.items():
                if len(data) == 2:
                    fc_text = f"[{clean_text(cat)}]\n{clean_text(data[0])}\nRemedy: {clean_text(data[1])}\n"
                    pdf.chapter_body(fc_text)

        # --- 10. TIMELINE FORECAST ---
        pdf.add_page()
        pdf.chapter_title("Vimshottari Dasha (Timeline Forecast)")
        
        pd_info = kwargs.get('pd_info', {})
        if pd_info:
            pdf.set_font('helvetica', 'B', 11)
            pdf.set_text_color(22, 160, 133)
            current_phase_txt = f"Current Phase: {clean_text(pd_info.get('MD', ''))} Mahadasha, {clean_text(pd_info.get('AD', ''))} Antardasha (Until {clean_text(pd_info.get('End', ''))})"
            pdf.cell(0, 10, current_phase_txt, 0, 1, 'L')
            pdf.ln(5)

        dasha_data = kwargs.get('mahadasha_data', [])
        pdf.set_font('helvetica', 'B', 10)
        pdf.set_fill_color(240, 240, 240)
        pdf.set_text_color(44, 62, 80)
        pdf.cell(30, 8, "Age", 1, 0, 'C', 1)
        pdf.cell(40, 8, "Years", 1, 0, 'C', 1)
        pdf.cell(30, 8, "Phase", 1, 0, 'C', 1)
        pdf.ln()
        
        pdf.set_font('helvetica', '', 10)
        pdf.set_text_color(50, 50, 50)
        for row in dasha_data:
            pdf.cell(30, 8, clean_text(str(row.get('Age (From-To)', ''))), 1, 0, 'C')
            pdf.cell(40, 8, clean_text(str(row.get('Years', ''))), 1, 0, 'C')
            pdf.cell(30, 8, clean_text(str(row.get('Mahadasha', ''))), 1, 0, 'C')
            pdf.ln()

        # Generate Byte output safely
        pdf_bytes = bytes(pdf.output())
        return pdf_bytes, None

    except Exception as e:
        return None, str(e)
